# Generated by Django 5.2.15 on 2026-07-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('phone_display', models.CharField(blank=True, max_length=40)),
                ('emergency_phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('maps_link', models.URLField(blank=True)),
                ('languages', models.JSONField(default=list)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
