# Generated by Django 5.2.15 on 2026-07-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='accepted_insurance',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='clinic',
            name='booking_horizon_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='clinic',
            name='cancellation_policy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='min_notice_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='clinic',
            name='new_patient_form_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='slot_granularity_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(max_length=32)),
                ('preferred_channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=16)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('language_pref', models.CharField(default='en', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('no_show_count', models.PositiveIntegerField(default=0)),
                ('sms_consent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_consent_source', models.CharField(blank=True, max_length=64)),
                ('sms_consent_text', models.TextField(blank=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinics.clinic')),
            ],
            options={
                'indexes': [models.Index(fields=['clinic', 'phone_e164'], name='clinics_pat_clinic__93c313_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'phone_e164'), name='uniq_clinic_phone')],
            },
        ),
    ]
