# Generated by Django 5.2.15 on 2026-07-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_accepted_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='quiet_hours_end',
            field=models.TimeField(default='21:00'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='quiet_hours_start',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='reminders_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
