# Generated by Django 5.2.15 on 2026-07-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_quiet_hours_end_clinic_quiet_hours_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='owner_digest_hour',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner_phone_e164',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
