# Generated by Django 5.2.15 on 2026-07-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinic_owner_digest_hour_clinic_owner_phone_e164'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='no_show_recovery_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
