# Generated by Django 5.2.15 on 2026-07-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_monthlyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='marketing_min_interval_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='clinic',
            name='recalls_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_marketing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
