# Generated by Django 5.2.15 on 2026-07-07 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinic_marketing_min_interval_days_and_more'),
        ('scheduling', '0005_service_practitioners'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='preferred_practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferring_patients', to='scheduling.practitioner'),
        ),
    ]
