# Generated by Django 5.2.15 on 2026-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_patient_preferred_practitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='prompt_variant',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
