# Generated by Django 5.2.15 on 2026-07-05 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=16)),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=4)),
                ('provider_message_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('from_number', models.CharField(blank=True, max_length=32)),
                ('to_number', models.CharField(blank=True, max_length=32)),
                ('body', models.TextField(blank=True)),
                ('message_type', models.CharField(default='text', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'created_at'], name='messaging_m_clinic__a343c9_idx')],
            },
        ),
    ]
