# Generated by Django 5.2.15 on 2026-07-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='interactive',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
