# Generated by Django 5.2.15 on 2026-07-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_scheduledmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='kind',
            field=models.CharField(choices=[('confirmation', 'Booking confirmation'), ('reminder_24h', '24-hour reminder'), ('reminder_2h', '2-hour reminder'), ('thank_you', 'Post-appointment thank-you')], max_length=24),
        ),
    ]
