# Generated by Django 5.2.15 on 2026-07-06 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinic_owner_digest_hour_clinic_owner_phone_e164'),
        ('messaging', '0005_alter_scheduledmessage_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_digests', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'date'), name='uniq_clinic_digest_date')],
            },
        ),
    ]
