# Generated by Django 5.2.15 on 2026-07-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_ownerdigest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('service', 'Service (in-session)'), ('utility', 'Utility'), ('marketing', 'Marketing'), ('authentication', 'Authentication')], default='service', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='cost_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='MessageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=16)),
                ('category', models.CharField(choices=[('service', 'Service (in-session)'), ('utility', 'Utility'), ('marketing', 'Marketing'), ('authentication', 'Authentication')], max_length=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'category'), name='uniq_channel_category_rate')],
            },
        ),
    ]
