# Generated by Django 5.2.15 on 2026-07-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_seed_default_message_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
