# Generated by Django 5.2.15 on 2026-07-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_message_delivery_error_message_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='kind',
            field=models.CharField(choices=[('confirmation', 'Booking confirmation'), ('reminder_24h', '24-hour reminder'), ('reminder_2h', '2-hour reminder'), ('thank_you', 'Post-appointment thank-you'), ('recovery_sameday', 'No-show same-day recovery'), ('recovery_rebook', 'No-show rebooking offer')], max_length=24),
        ),
    ]
