# Generated by Django 5.2.15 on 2026-07-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinic_no_show_recovery_enabled'),
        ('messaging', '0010_alter_scheduledmessage_kind'),
        ('scheduling', '0003_appointment_recovered_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_token', models.CharField(max_length=160)),
                ('slot_starts_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=12)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_offers', to='clinics.clinic')),
                ('freed_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_offers', to='scheduling.appointment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
