# Generated by Django 5.2.15 on 2026-07-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_waitlistoffer'),
        ('scheduling', '0004_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistoffer',
            name='waitlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='scheduling.waitlist'),
        ),
        migrations.AddIndex(
            model_name='waitlistoffer',
            index=models.Index(fields=['status', 'scheduled_for'], name='messaging_w_status_c31db0_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistoffer',
            index=models.Index(fields=['status', 'offer_expires_at'], name='messaging_w_status_6019b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='waitlistoffer',
            constraint=models.UniqueConstraint(fields=('waitlist', 'freed_appointment'), name='uniq_waitlist_freed_appointment'),
        ),
    ]
