# Generated by Django 5.2.15 on 2026-07-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinic_marketing_min_interval_days_and_more'),
        ('messaging', '0012_waitlistoffer_waitlist_and_more'),
        ('scheduling', '0004_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('interval_days', models.PositiveIntegerField()),
                ('window_days', models.PositiveSmallIntegerField(default=7)),
                ('template_name', models.CharField(max_length=64)),
                ('message_override', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_rules', to='clinics.clinic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_rules', to='scheduling.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecallCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='running', max_length=12)),
                ('eligible', models.PositiveIntegerField(default=0)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('projected_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_campaigns', to='clinics.clinic')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='messaging.recallrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecallSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='messaging.recallcampaign')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_sends', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_sends', to='clinics.patient')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='messaging_r_status_87916a_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'patient'), name='uniq_campaign_patient_recall')],
            },
        ),
    ]
