# Generated by Django 5.2.15 on 2026-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='false_confirmation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
