# Generated by Django 5.2.15 on 2026-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
