# Generated by Django 5.2.15 on 2026-07-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_appointment_patient_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recovered_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_bookings', to='scheduling.appointment'),
        ),
    ]
