# Generated by Django 5.2.15 on 2026-07-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinic_no_show_recovery_enabled'),
        ('scheduling', '0003_appointment_recovered_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('time_preference', models.CharField(choices=[('any', 'Any time'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='any', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offered', 'Offered'), ('booked', 'Booked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='clinics.patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='scheduling.practitioner')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='scheduling.service')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['clinic', 'service', 'status'], name='scheduling__clinic__c37d57_idx')],
            },
        ),
    ]
