# Generated by Django 5.2.15 on 2026-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='practitioners',
            field=models.ManyToManyField(blank=True, related_name='services', to='scheduling.practitioner'),
        ),
    ]
